# Generated by Django 5.2.6 on 2025-09-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Không hiển thị'), ('hot', 'Hot'), ('sale', 'Giảm giá'), ('sold_out', 'Hết hàng')], default='', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
